### ISSUE TITLE
try using the relesed model

### ISSUE THREAD

**Issue by chenbaruchchen** [apacha/MusicObjectDetector-TF#11]
try using the relesed model
tf cant load pb file

while saving the model - it create filder with asset and Varibels

**Comment by apacha** [comment]
Can you please provide information which TF version you're using?

**Comment by chenbaruchchen** [comment]
2.11.0


in the Dockerfile for building standalone metaion this project using 1.5.1
but i didnt found docs for that version


anyway i love your project

**Comment by chenbaruchchen** [comment]
oops still dont close
