### ISSUE TITLE
can your model be used to determine if two pieces of music are the same?

### ISSUE THREAD

**Issue by carljonghms** [apacha/MusicObjectDetector-TF#13]
I'm trying to build code to determine if two pieces of music are the same, looking at their pngs.  I've tried imagehash, but it didn't do a good job. 

The question I have about your model is: I have one of the measures where the notes are the same, but they are not on the same beats.  I understand your software would be able to recognize the notes.  Would it be able to recognize the order of the notes?

Thanks,

**Comment by apacha** [comment]
No, unfortunately the system would only give you the bounding-boxes of each symbol, not their musical order. Technically speaking, you could order the bounding boxes by their x- and y-axis, but that might not be always correct and it also wouldn't guarantee that the notes of two different measures would be the same.  

If you want to compare whether two measures contain the same music, have a look at https://publik.tuwien.ac.at/files/publik_282966.pdf - maybe that's what you're looking for.
