### ISSUE TITLE
Seeking help for an error

### ISSUE THREAD

**Issue by manggu** [apacha/MusicObjectDetector-TF#7]
When I try to create the Tensorflow Records by 'python create_muscima_tf_record.py --data_dir=data/training_validation_test --set=training --annotations_dir=Full_Page_Annotations --output_path=data/all_classes_writer_independent_split/training.record --label_map_path=mapping_all_classes.txt', I got ModuleNotFoundError: No module named 'object_detection'. Does somebody know how I can fix this? Thanks a lot.

**Comment by apacha** [comment]
This error is thrown if you didn't make the modules available. Check out https://github.com/apacha/MusicObjectDetector-TF#permanently-linking-the-source-code-as-pip-package for instructions how to build and link the module permanently into your python environment.
